# .github/workflows/caller-workflow.yml
name: Build Docker Images, JAR & WAR artifacts; and Push to JFrog Artifactory

on:
  push:
    branches:
      - main

jobs:
  build-jars:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [jar-service1, jar-service2]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR for ${{ matrix.module }}
        run: |
          cd ${{ matrix.module }}
          mvn clean package -DskipTests

      - name: Upload JAR to GitHub (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.module }}-jar
          path: ${{ matrix.module }}/target/*.jar

      - name: Push JAR to JFrog
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        run: |
          JAR_FILE=$(ls ${{ matrix.module }}/target/*.jar | head -n 1)
          curl -u "$JFROG_USERNAME:$JFROG_PASSWORD" \
               -T "$JAR_FILE" \
               "https://hanu14.jfrog.io/artifactory/ssd-jar/${{ matrix.module }}/$(basename $JAR_FILE)"

  build-wars:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [war-service1, war-service2]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build WAR for ${{ matrix.module }}
        run: |
          cd ${{ matrix.module }}
          mvn clean package -DskipTests

      - name: Upload WAR to GitHub (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.module }}-war
          path: ${{ matrix.module }}/target/*.war

      - name: Push WAR to JFrog
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
        run: |
          WAR_FILE=$(ls ${{ matrix.module }}/target/*.war | head -n 1)
          curl -u "$JFROG_USERNAME:$JFROG_PASSWORD" \
               -T "$WAR_FILE" \
               "https://hanu14.jfrog.io/artifactory/ssd-war/${{ matrix.module }}/$(basename $WAR_FILE)"


  build-docker:
    strategy:
      matrix:
        include:  
          - name: "alpine1"
            context: "./alpine1"
            dockerfile_path: "./alpine1/Dockerfile"
            repository: "hanu14.jfrog.io/ssd-docker"
            image_tag: "${{ github.run_id }}"
          - name: "alpine2"
            context: "./alpine2"
            dockerfile_path: "./alpine2/Dockerfile"
            repository: "hanu14.jfrog.io/ssd-docker"
            image_tag: "${{ github.run_id }}"

    uses: girichinna27/image-file-worker/.github/workflows/worker-workflow.yml@main
    with:
      image_name: ${{ matrix.name }}
      context: ${{ matrix.context }}
      dockerfile_path: ${{ matrix.dockerfile_path }}
      image_tag: ${{ matrix.image_tag }}
      registry: 'hanu14.jfrog.io'
      org: "opsmx"
      application_tags: "v1.0"
      artifactory_url: ${{ matrix.repository }}

    secrets:
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
      UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
      SSD_TEAM_TOKEN: ${{ secrets.SSD_TEAM_TOKEN }}
